spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5431/mydb
spring.sql.init.mode=always
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.remote.secret=mysecret


server.servlet.session.timeout=1800
server.servlet.session.cookie.http-only=true
# server.servlet.session.cookie.secure=false # https true

server.servlet.session.cookie.name=SESSIONID

logging.level.com.example.demo=DEBUG
